before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
      - darwin

archives:
  - format_overrides:
      - goos: windows
        format: zip

checksum:
  disable: true

changelog:
  skip: true