before:
  hooks:
    - go mod tidy

builds:
  - id: windows
    env:
      - CGO_ENABLE=1
    goos:
        - windows
  - id: other
    env:
      - CGO_ENABLED=0
    goos:
        - linux
        - darwin

archives:
  - format_overrides:
      - goos: windows
        format: zip

checksum:
  disable: true

changelog:
  skip: true