name: Release

on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - name: Set env vars
        run: |
            echo "CGO_ENABLED=1" >> $GITHUB_ENV
      - run: go build .
